version: '2'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_USER_PWD: ${DB_USER_PWD}
      DB_ROOT_PWD: ${DB_ROOT_PWD}
    volumes:
      - mariadb:/var/lib/mysql/
    networks:
      - inceptionNetwork
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html/wordpress
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_USER_PWD: ${DB_USER_PWD}
      DB_ROOT_PWD: ${DB_ROOT_PWD}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PWD: ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_USER_PWD: ${WP_USER_PWD}
      WP_DB_HOST: ${WP_DB_HOST}
      WP_URL: ${WP_URL}
    networks:
      - inceptionNetwork
    depends_on:
      - mariadb
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inceptionNetwork
    ports:
      - 443:443
    restart: always

networks:
  inceptionNetwork:
    driver: bridge

volumes:
  wordpress:
    driver_opts:
      type: none
      o: bind
      device: /home/msodor/data/wordpress
    name: wordpress
  mariadb:
    driver_opts:
      type: none
      o: bind
      device: /home/msodor/data/mariadb
    name: mariadb
